language: python
sudo: false
addons:
  apt:
    packages:
      - libtidy-dev
python:
  - "3.5"
install: pip install . pep8 pylint
script: pep8 readembedability && pylint readembedability && python -m unittest
